/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface QueryOptions {
  includeTitle?: boolean
  includeOwnerPid?: boolean
}
export interface WindowRect {
  left: number
  top: number
  right: number
  bottom: number
}
export interface WindowInfo {
  id: string
  rect: WindowRect
  isVisible: boolean
  isMinimized: boolean
  isCloaked: boolean
  exStyle: number
  title?: string
  ownerPid?: number
}
export declare function listWindows(options?: QueryOptions | undefined | null): Array<WindowInfo>
export declare function getWindow(id: string, options?: QueryOptions | undefined | null): WindowInfo | null
export declare function getWindowsAbove(id: string, options?: QueryOptions | undefined | null): Array<WindowInfo>
export declare function getForegroundWindow(options?: QueryOptions | undefined | null): WindowInfo | null
